# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20ef5d777eef0adfa98c5c6677b2d0306189f778edec0892cd3d123f1efc1ced388436b9af37ce9659ef09510dca45aaef15833819a717db6fc57eb2c9bf8845

test:
  secret_key_base: 27fc6ccfa1d7bf781a27b8d7a0d5058225eb5db6b51e6d6fa87a90e74fe502d980563811016ba928c2ed750edcca1e22959d26eed52ed3c751e97a760c41cd9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
